project/conversation/urls.py
from django.urls import path 

from . import views

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/<int:item_pk>/',views.new_conversation, name='new'),
]

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'  ),
    path('contact/' , views.contact, name='contact'),
    path('signup/' , views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
]

project/dashboard/urls.py
from django.urls import path

from . import views
app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
]

project/item/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'  ),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'  ),
    path('<int:pk>/delete/', views.delete, name='delete'  ),
    path('<int:pk>/edit/', views.edit, name='edit'  ),
    path('items/', views.items, name='items'  ),
   
] 

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('core.urls')  ),
    path('items/',include('item.urls') ),
    path('dashboard/', include('dashboard.urls')  ),
    path('inbox/', include('conversation.urls')  ),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class':'w-full py-4 px-5 rounded-xl'
                }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class':'w-full py-4 px-5 rounded-xl'
                }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2' )

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class':'w-full py-4 px-5 rounded-xl'
                }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your email',
        'class':'w-full py-4 px-5 rounded-xl'
                }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class':'w-full py-4 px-5 rounded-xl'
                }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat your password',
        'class':'w-full py-4 px-5 rounded-xl'
                }))

project/core/views.py
from django.shortcuts import render,redirect
from item.models import Category, Item
from .forms import SignupForm
# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html',{
        'items':items,
        'categories':categories,
    })

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html',{
        'form':form
    })

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}  Reis567</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-bold">Magazine Luis</a>
        <div class="space-x-6">
            {% if request.user.is_authenticated %}
            <a href="/" class="text-lg font-semibold hover:text-gray-500 transition easy-in-out duration-500">Bem vindo {{user.username}} </a>
            {% endif %}
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500 transition easy-in-out duration-500">Navegar </a>


            {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition easy-in-out duration-500">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-xl hover:bg-sky-700 transition easy-in-out duration-500">Dashboard</a>
            <a href="{% url 'item:new' %}" class="px-6 py-3 text-lg font-semibold bg-purple-500 text-white rounded-xl hover:bg-sky-700 transition easy-in-out duration-500">Adicionar produto</a>

            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition easy-in-out duration-500">Sign-up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-xl hover:bg-sky-700 transition easy-in-out duration-500">Login</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        
        {% block content %}
        {% endblock content %}

    </div>


    <footer class="py-6 px-6 flex justify-between bg-gray-800">

        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">
                Sobre
            </h3>
            <p class="text-lg text-gray-500">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione exercitationem, fugiat aliquam magnam autem, nam incidunt animi expedita laborum corrupti eveniet! Repellendus obcaecati quisquam laboriosam voluptatibus inventore magnam, sint illum!
            </p>

        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">
                Menu
            </h3>
            <ul class="space-y-2">
                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="">Sobre</a>
                </li>

                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="{% url 'core:contact' %}">Contato</a>
                </li>

                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="">Politica de privacidade</a>
                </li>

                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="">Termos de uso</a>
                </li>

            </ul>

        </div>
    </footer>
</body>
</html>

project/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}Contato - {% endblock title %}
{% block content %}
<h1>Contact Botafogo de futebol e regatas</h1>
{% endblock content %}

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">
        Itens mais recentes
        
    </h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img class="rounded-t-xl" src="{{item.image.url}}" alt="">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl ">
                            {{item.name}}
                        </h2>
                        <p class="text-gray-500">
                            Preço : R$ {{item.price}}
                        </p>

                    </div>
                </a>
            </div>
        {% endfor %}

    </div>

</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">
        Categorias
        
    </h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl ">
                        {{category.name}}
                    </h2>
                    <p class="text-gray-500">
                        {{category.items.count}} itens
                    </p>

                </div>
            </a>
        </div>
        
        {% endfor %}
    </div>

</div>
{% endblock content %}

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login - {% endblock title %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">
        Login
    </h1>

    <form action="" method="post">
        {% csrf_token %}
        

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Username</label><br>
            {{form.username}}

        </div>

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Password</label><br>
            {{form.password}}

        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
            {{form.non_field_errors}}

        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg text-white bg-teal-500 hover:bg-teal-700 rounded-xl transition easy-in-out duration-500">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

project/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Signup - {% endblock title %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">
        Sign up
    </h1>

    <form action="" method="post">
        {% csrf_token %}
        

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Username</label><br>
            {{form.username}}

        </div>
        <div class="mb-3">
            <label class="inline-block mb-2" for="">Email</label><br>
            {{form.email}}

        </div>
        <div class="mb-3">
            <label class="inline-block mb-2" for="">Password</label><br>
            {{form.password1}}

        </div>
        <div class="mb-3">
            <label class="inline-block mb-2" for="">Repeat Password</label><br>
            {{form.password2}}

        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
            {{form.non_field_errors}}

        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl transition easy-in-out duration-500">
            Submit
        </button>
    </form>
</div>

{% endblock content %}